modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/kyber-6/mobs-of-mythology-mod/issues"
license = "MIT"

[[mods]]
modId = "mobs_of_mythology"
version = "${version}"
displayName = "Mobs of Mythology"
authors = "kyber-6, Pixel Dream Studios"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mobs-of-mythology"
description = '''
Discover a World of Mythological Creatures in Minecraft!
'''
logoFile = "icon.png"

[[dependencies.mobs_of_mythology]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobs_of_mythology]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobs_of_mythology]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mobs_of_mythology]]
modId = "azurelib"
type = "required"
versionRange = "[2.3.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobs_of_mythology]]
modId = "smartbrainlib"
type = "required"
versionRange = "[1.14.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mobs_of_mythology.mixins.json"
